branch-defaults:
  default:
    environment: my-flask-env
global:
  application_name: my-flask-app
  default_ec2_keyname: aws-eb
  default_platform: Python 3.8
  include_git_submodules: true
  instance_profile: aws-elasticbeanstalk-ec2-role
  platform_name: null
  platform_version: null
  region: us-west-2
  repository: null
  sc: git
